# Site settings
title: Trevor Summerfield
email: trevor@trevorsummerfield.com
description: > # this means to ignore newlines until "baseurl:"
  Trevor Summerfield's GitHub Pages Site
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tsums.github.io    " # the base hostname & protocol for your site
github_username:  tsums

# Build settings
markdown: kramdown
